apiVersion: v1
kind: Namespace
metadata:
  namespace: eshoponweb-user007
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoponweb-deployment
  labels:
    app: eshoponweb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eshoponweb
  template:
    metadata:
      labels:
        app: eshoponweb
    spec:
      containers:
        - name: eshoponweb-app
          image: acrnm02test.azurecr.io/eshoponweb-user-007:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
